### ISSUE TITLE
Cursor App

### ISSUE THREAD

**Issue by tigerbatchelor** [micku7zu/QuickCursor#1]
It tends to go wonky when you rotate to portrait mode. Moto - - Edge. It's good other than that

**Comment by micku7zu** [comment]
Thanks for feedback. What does it mean "go wonky"? Can you please describe? Do you setup the layout for portrait and for landscape mode differently?

Can you enable Quick Cursor Settings -> Debug -> Debug visuals and post a screenshot in portrait and in landscape? 

Try to explain the issue more so I can reproduce the issue and fix it.

Thanks!

**Comment by tigerbatchelor** [comment]
I can try to screen record it if you like.

**Comment by micku7zu** [comment]
Sure, a screen record would help. Enable Debug Visuals from Settings -> Debug for better visibility. Thanks!

**Comment by tigerbatchelor** [comment]
1:12:06.850: Try turnOn()
01:12:06.887: Try turnOn()
01:12:13.715: Try turnOn()
01:12:13.744: Try turnOn()
01:12:13.769: Try turnOn()
01:12:14.043: New orientation: Portrait
01:12:14.043: Try turnOn()
01:12:14.700: Try turnOn()
01:12:14.731: Try turnOn()
01:12:14.751: New orientation: Landscape
01:12:14.751: Try turnOn()
01:12:14.783: Try turnOn()
01:12:16.297: Try turnOn()
01:12:16.335: Try turnOn()
01:12:16.369: Try turnOn()
01:12:17.254: Try turnOn()
01:12:17.279: Try turnOn()
01:12:17.322: Try turnOn()
01:12:18.768: New orientation: Portrait
01:12:18.768: Try turnOn()
01:13:25.804: updateEventTypes: 4194336
01:13:25.807: turnOff(): PAUSED_KEYBOARD
01:15:46.083: updateEventTypes: 32
01:15:46.085: Try turnOn()
01:16:02.267: updateEventTypes: 4194336
01:16:02.268: turnOff(): PAUSED_KEYBOARD
01:16:27.718: updateEventTypes: 32
01:16:27.720: Try turnOn()
01:17:05.921: updateEventTypes: 4194336
01:17:05.923: turnOff(): PAUSED_KEYBOARD
01:17:07.503: updateEventTypes: 32
01:17:07.510: Try turnOn()
01:33:46.165: updateEventTypes: 4194336
01:33:46.167: turnOff(): PAUSED_KEYBOARD
01:33:48.387: updateEventTypes: 32
01:33:48.396: Try turnOn()
01:50:49.813: updateEventTypes: 4194336
01:50:49.816: turnOff(): PAUSED_KEYBOARD
01:51:21.954: updateEventTypes: 32
01:51:21.961: Try turnOn()
01:52:06.802: New orientation: Landscape
01:52:06.802: Try turnOn()
01:52:11.863: New orientation: Portrait
01:52:11.863: Try turnOn()
01:52:19.467: Try turnOn()
01:52:22.113: Try turnOn()
01:53:50.835: Try turnOn()
01:53:50.866: Try turnOn()
01:53:50.974: Try turnOn()
01:53:51.003: Try turnOn()
01:53:51.024: New orientation: Landscape
01:53:51.024: Try turnOn()
01:53:51.049: Try turnOn()
01:53:59.242: Try turnOn()
01:53:59.277: Try turnOn()
01:53:59.312: Try turnOn()
01:54:00.194: Try turnOn()
01:54:00.226: Try turnOn()
01:54:00.255: Try turnOn()
01:54:02.247: Try turnOn()
01:54:02.287: Try turnOn()
01:54:02.324: Try turnOn()
01:54:02.612: New orientation: Portrait
01:54:02.612: Try turnOn()
01:54:03.304: Try turnOn()
01:54:03.337: Try turnOn()
01:54:03.367: New orientation: Landscape
01:54:03.367: Try turnOn()
01:54:03.401: Try turnOn()
01:54:05.034: Try turnOn()
01:54:05.073: Try turnOn()
01:54:05.112: Try turnOn()
01:54:05.343: New orientation: Portrait
01:54:05.343: Try turnOn()
01:54:06.066: Try turnOn()
01:54:06.100: Try turnOn()
01:54:06.119: New orientation: Landscape
01:54:06.119: Try turnOn()
01:54:06.145: Try turnOn()
01:54:08.675: Try turnOn()
01:54:08.708: Try turnOn()
01:54:08.880: Try turnOn()
01:54:08.976: New orientation: Portrait
01:54:08.977: Try turnOn()
01:54:09.649: Try turnOn()
01:54:09.686: Try turnOn()
01:54:09.720: Try turnOn()
01:54:09.938: New orientation: Landscape
01:54:09.938: Try turnOn()
01:54:12.114: New orientation: Portrait
01:54:12.114: Try turnOn()
01:54:51.704: updateEventTypes: 4194336
01:54:51.705: turnOff(): PAUSED_KEYBOARD
01:54:56.543: updateEventTypes: 32
01:54:56.545: Try turnOn()
01:57:46.795: updateEventTypes: 4194336
01:57:46.796: turnOff(): PAUSED_KEYBOARD
01:57:53.152: updateEventTypes: 32
01:57:53.153: Try turnOn()
01:57:58.540: updateEventTypes: 4194336
01:57:58.543: turnOff(): PAUSED_KEYBOARD
01:58:11.090: updateEventTypes: 32
01:58:11.092: Try turnOn()
01:58:38.128: updateEventTypes: 4194336
01:58:38.130: turnOff(): PAUSED_KEYBOARD
01:59:12.943: updateEventTypes: 32
01:59:12.944: Try turnOn()
01:59:58.918: updateEventTypes: 4194336
01:59:58.926: turnOff(): PAUSED_KEYBOARD
02:00:17.299: updateEventTypes: 32
02:00:17.300: Try turnOn()
02:00:44.339: updateEventTypes: 4194336
02:00:44.341: turnOff(): PAUSED_KEYBOARD
02:00:48.065: updateEventTypes: 32
02:00:48.068: Try turnOn()
02:04:52.186: updateEventTypes: 4194336
02:04:52.189: turnOff(): PAUSED_KEYBOARD
02:04:53.418: updateEventTypes: 32
02:04:53.419: Try turnOn()
02:05:43.878: updateEventTypes: 4194336
02:05:43.879: turnOff(): PAUSED_KEYBOARD
02:05:47.290: updateEventTypes: 32
02:05:47.293: Try turnOn()
02:10:33.887: updateEventTypes: 4194336
02:10:33.891: turnOff(): PAUSED_KEYBOARD
02:10:53.987: updateEventTypes: 32
02:10:53.989: Try turnOn()
02:12:36.661: updateEventTypes: 4194336
02:12:36.664: turnOff(): PAUSED_KEYBOARD
02:12:43.879: updateEventTypes: 32
02:12:43.879: Try turnOn()
02:13:21.227: New orientation: Landscape
02:13:21.228: Try turnOn()
02:13:25.233: Try turnOn()
02:13:25.287: Try turnOn()
02:13:25.329: Try turnOn()
02:13:26.279: Try turnOn()
02:13:26.308: Try turnOn()
02:13:26.339: Try turnOn()
02:13:34.193: Try turnOn()
02:13:34.241: Try turnOn()
02:13:34.279: Try turnOn()
02:13:35.235: Try turnOn()
02:13:35.265: Try turnOn()
02:13:35.300: Try turnOn()
02:13:36.348: New orientation: Portrait
02:13:36.348: Try turnOn()
02:13:56.959: Try turnOn()
02:13:59.257: Try turnOn()
02:14:00.026: Try turnOn()
02:14:00.821: Try turnOn()
02:14:34.912: updateEventTypes: 4194336
02:14:34.927: turnOff(): PAUSED_KEYBOARD
02:14:39.159: updateEventTypes: 32
02:14:39.173: Try turnOn()
02:14:45.469: Try turnOn()
02:14:46.547: Try turnOn()

**Comment by tigerbatchelor** [comment]
Does that help?

**Comment by micku7zu** [comment]
Not really, "Debug visuals" would help with a screen record. Because I don't know what exactly is the issue, I need to see it to understand what "go wonky" means. And after that we can debug why it happens, but first I need to understand what happens. Thanks! 

A screen record would be perfect.

**Comment by tigerbatchelor** [comment]
When I set my screen to landscape it doesn't stop rotating from landscape
to normal.

**Comment by micku7zu** [comment]
I would like to solve the issue but I still don't understand exactly what happens wrong. 
Quick Cursor have two setups: one for landscape, one for portrait. You can set each mode in any way you like, even turn off in some orientation.

I don't know exactly what you expect to happpen.

**Comment by tigerbatchelor** [comment]
When I rotate it to portrait it goes to landscape. BUT ONLY when I activate
landscape mode. I'm sorry about the language barrier.

**Comment by micku7zu** [comment]
Hmmmmm, this is really weird. First time someone reported something like this. What device do you have and what Android version?

**Comment by tigerbatchelor** [comment]
Moto Edge running android 11

**Comment by micku7zu** [comment]
Really strange, can't reproduce the issue on any device I own. 

Can you send me a screen record with the issue when the "Debug visuals" are turned on? Thanks!

**Comment by tigerbatchelor** [comment]
https://photos.app.goo.gl/9j7GBmKwbrodwegy7

**Comment by micku7zu** [comment]
Oh, I understand know. It happens only on the Quick Cursor settings. I thought the triggers are working incorrectly when you try to use the app outside of Quick Cursor, when you want to use the cursor in real situation.

Thanks for screenshare, I will investigate the issue now!

**Comment by tigerbatchelor** [comment]
Fuck yeah!!

**Comment by tigerbatchelor** [comment]
I'm glad I could help

**Comment by micku7zu** [comment]
Found the bug, I successfully reproduced it on my device, and I fixed it.

It will come with the next update (I'm not sure when it will be available on Play Store).

Thanks for reporting the issue!

**Comment by tigerbatchelor** [comment]
You're welcome 👋👋
