### ISSUE TITLE
Gesture recorder length

### ISSUE THREAD

**Issue by Izhaar96** [micku7zu/QuickCursor#10]
Can you make gesture recorder more longer like before. Now its hard to move some apps of dragging something. Its take less 3 sec now when use gesture recorder. Hope you can fix this.

**Comment by micku7zu** [comment]
Yes, I will fix this in the next update. Thanks!

**Comment by micku7zu** [comment]
Fixed the issue in [Beta Release 1.21.7 (version 178)](https://github.com/micku7zu/QuickCursor/releases/tag/178).

Installing **random APKs from internet it is not recommended**, so if you are not an advanced user, wait for the update to arrive through Play Store.

The beta is available on [Github releases](https://github.com/micku7zu/QuickCursor/releases)/[Telegram group https://t.me/quickcursor](https://t.me/quickcursor), or you can wait until the public release is available through Play Store.
