### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by jcperil** [micku7zu/QuickCursor#17]
Can you add QuickCursor to F-Droid? The free tier (non-pro) version at least.

[This is the inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) that must be met to be able to submit. More info about submitting can be [found here](https://f-droid.org/en/contribute/).

[Here is the issue tracker](https://gitlab.com/fdroid/rfp/-/issues) to request your package to be available on F-Droid. After submitting, they can assist on what is needed to be done (if anything) to get it on F-Droid.

**Comment by micku7zu** [comment]
> All applications in the repository must be Free, Libre and Open Source Software (FLOSS) – for example, released under a GPL or Apache license.

Unfortunately, Quick Cursor is not Open Source, it can't be added to F-Droid.

I don't have in plan to open source it yet.
