### ISSUE TITLE
left hand mode for floating tracker 

### ISSUE THREAD

**Issue by connercms** [micku7zu/QuickCursor#20]
Hello, and thank you for a great, useful app. I unlocked pro version to use the floating tracker but it appears it can only be set on the right side of the screen? Or can this be configured to appear on left side instead. If so, i am overlooking the settings to configure this. If not, this would be a useful option for left handed users.

**Comment by micku7zu** [comment]
Hi, the floating tracker can be drag and dropped on the left side. The position of the floating tracker is dynamic, like a chat bubble.
