### ISSUE TITLE
Not working with Android 14 - Pixel

### ISSUE THREAD

**Issue by Amjadalbaye** [micku7zu/QuickCursor#21]
After an update in Google pixel 6, android 14 doesn't let the app to work. There is no way to trigger the cursor .
Please help

**Comment by micku7zu** [comment]
Hey, thanks for reporting the issue. I've created a new issue to centralize all the info we know so far, if you can help with more details, please join the discussion here: https://github.com/micku7zu/QuickCursor/issues/22
