### ISSUE TITLE
Bug - add apps to Whitelist & Blacklist not Working 

### ISSUE THREAD

**Issue by Cod3rQwerty** [micku7zu/QuickCursor#24]
When trying to add an app to whitelist/blacklist, user gets prompted to enable accessibility service despite it already being enabled.

**Comment by micku7zu** [comment]
Can you please attach a screen record with this? What device and what Android version do you have? Thanks!

**Comment by Cod3rQwerty** [comment]
I am using a Nokia X30 5G with android version 14 and free version of the app. Here is the screen record:

https://github.com/user-attachments/assets/4629cb4c-3a4b-4df5-9281-93f828a597c1

**Comment by Cod3rQwerty** [comment]
Oh and also I'm using the Niagara launcher, not the default one.

**Comment by micku7zu** [comment]
Oh I see now, the app is crashing when it tries to display the list of apps, that's why you see that message with accessibility service. Do you know how to grab a logcat? That would help me to pinpoint the exact issue.

**Comment by Cod3rQwerty** [comment]
No, I don't know how to do that

**Comment by micku7zu** [comment]
No problem. Thanks for all the info. I will try to replicate the bug and see what's crashing the app on your case in that situation. Thanks again! I will try to fix it as soon as possible.

**Comment by Cod3rQwerty** [comment]
Ok, good luck and thank you!

**Comment by micku7zu** [comment]
Found the issue and fixed it✅. **Thanks!** 

I will release the new version today but it will take some time to arrive to all users through Play Store.

**Comment by Cod3rQwerty** [comment]
Okay, thank you for fixing it!

**Comment by micku7zu** [comment]
![image](https://github.com/user-attachments/assets/462fe54b-3b3b-40e8-9bda-1b0ab96527e4)
