### ISSUE TITLE
External monitor

### ISSUE THREAD

**Issue by lysleung** [micku7zu/QuickCursor#26]
Hi there. 

I try your app but the cursor won't go to scren in my usb-C external monitor.

Any help?

This is the guide i followed to set my Android's Force Desktop Mode.

Thanks.

**Comment by micku7zu** [comment]
Hi,

Unfortunately Quick Cursor was not made to work on external screens, and there is a reason behind this. Quick Cursor main focus is to help you use **your phone with one hand**. I know that this functionality is similar with a touchpad controling a mouse on a screen, but the actual needs to control a mouse on a screen is different than what Quick Cursor does and this would probably be better as a separate app. 

The config is completely different for Quick Cursor on a mobile device and on an external screen. The sensitivity and the mapping should be completely different and specific for an external display. It is out of scope of my app.

At the moment I won't implement any feature related to an external monitor, this should be a separate touchpad app, like Samsung does for Samsung Dex.

I'm sorry and I hope you understand.

Thanks!
