### ISSUE TITLE
Tapping stopped working

### ISSUE THREAD

**Issue by evnvc** [micku7zu/QuickCursor#28]
Hi, the tapping stopped working for me in the latest update. Tried resetting, force stop, restarting service, accessibility etc 
Long tap seems to work, in the sense it triggers the gesture recording, but no actual tap and hold. Quick Actions such as swipes also don't work.

Details:
App version 1.28.2
Device: Pixel 8 Pro
Software: Android 15, build number AP41.240823.009

**Comment by micku7zu** [comment]
Thanks for feedback! 

Unfortunately, this is another Pixel OS bug. The gesture replication doesn't work at the OS level.

You can try a device restart. 

If you find a way to replicate the issue, we can report this to Google, but I can't do anything at the app level to fix this. 

Sorry :(

**Comment by micku7zu** [comment]
When it was the latest Pixel OS update? Maybe the latest update introduced this bug.

**Comment by evnvc** [comment]
Weirdly enough, a restart fixed it 🥴 Feeling silly for not thinking of it. Will keep an eye out if it happens again to learn what triggers it. Many thanks for the quick reply!
